### ISSUE TITLE
Not compatible with browsers of earlier versions

### ISSUE THREAD

**Issue by rzdong** [jaywcjlove/rehype-attr#45]
version：2.1.2

code:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/19262880/209620448-16d37f8a-507c-4830-bd94-6f7083de8bc7.png">

![image](https://user-images.githubusercontent.com/19262880/209620544-01658adc-c78c-4b3e-b1be-aa6670bda184.png)

error:
Error.stack: SyntaxError: Unexpected token ."

**Comment by jaywcjlove** [comment]
@rzdong upgrade v2.1.3

**Comment by rzdong** [comment]
@jaywcjlove  Is there also a need to modify。: ) 
It might be handy to use babel

<img width="873" alt="image" src="https://user-images.githubusercontent.com/19262880/209795441-78f89bd7-f22d-4128-92be-6c20606ac40f.png">

**Comment by jaywcjlove** [comment]
@rzdong upgrade `v2.1.4`

**Comment by rzdong** [comment]
thanks a lot～～～～ : ）
